namespace BlazorAutoApp.Client.Features.Books.Shared;

public static class BookCoverDesignCatalog
{
    public static IReadOnlyList<BookCoverDesignDefinition> All { get; } =
    [
        new(
            Kind: BookCoverDesignKind.ClothHardback,
            Id: "cloth-hardback",
            Label: "Cloth Hardback",
            DemoTitleLines: ["The Great", "Gatsby"],
            DemoTitleY: 99,
            DemoTitleDy: "1.28em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Clean cloth hardback with a centered title plate, restrained page motion, and a quiet right-side page gutter.",
            CoverColors: new("#2f6f82", "#1f4e5f", "#123342"),
            PageColors: new("#fff9ed", "#f1e3cf", "#d6c8b8"),
            LineStroke: "#a99f91",
            Plate: BookCoverGeometry.CenteredPlate(62, 94, 88, 11, "#f8fafc", "#e0f2fe")),
        new(
            Kind: BookCoverDesignKind.DecorativeHardcover,
            Id: "decorative-hardcover",
            Label: "Decorative Hardcover",
            DemoTitleLines: ["Trace", "Back"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Premium celestial archive cover with brass foil orbits, quiet star marks, and a protected title plate.",
            CoverColors: new("#4c1d95", "#312e81", "#111827"),
            PageColors: new("#fff7ed", "#f1e7d7", "#d6d3d1"),
            LineStroke: "#a99f91",
            Plate: BookCoverGeometry.CenteredPlate(76, 86, 68, 10, "#f8fafc", "#f4d27a")),
        new(
            Kind: BookCoverDesignKind.FieldNotebook,
            Id: "field-notebook",
            Label: "Field Notebook",
            DemoTitleLines: ["Designing", "Reliable", "Systems"],
            DemoTitleY: 95,
            DemoTitleDy: "1.18em",
            DemoTitleFontSize: "11",
            DemoTitleFill: "#111827",
            Note: "Notebook-inspired cover with balanced ruling, dot markers, and four page tabs.",
            CoverColors: new("#0f766e", "#0f766e", "#134e4a"),
            PageColors: new("#fff9ed", "#f4ead9", "#d8d0c4"),
            LineStroke: "#a8a29e",
            Plate: BookCoverGeometry.CenteredPlate(74, 88, 72, 10, "#f0fdfa", "#ccfbf1")),
        new(
            Kind: BookCoverDesignKind.PrismAtlas,
            Id: "prism-atlas",
            Label: "Prism Atlas",
            DemoTitleLines: ["Vector", "Room"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Crisp geometric atlas cover with prism facets, inlay seams, and editorial registration marks.",
            CoverColors: new("#1e3a8a", "#312e81", "#111827"),
            PageColors: new("#f8fafc", "#e2e8f0", "#cbd5e1"),
            LineStroke: "#9ca3af",
            Plate: BookCoverGeometry.CenteredPlate(76, 86, 68, 8, "#f8fafc", "#67e8f9")),
        new(
            Kind: BookCoverDesignKind.DropletMonograph,
            Id: "droplet-monograph",
            Label: "Droplet Monograph",
            DemoTitleLines: ["Clear", "Signal"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#0f172a",
            Note: "Quiet monograph cover with a low water-drop mark, soft highlights, and calm negative space.",
            CoverColors: new("#0e7490", "#075985", "#0c4a6e"),
            PageColors: new("#ecfeff", "#dff4f8", "#cbd5e1"),
            LineStroke: "#94a3b8",
            Plate: BookCoverGeometry.CenteredPlate(76, 88, 68, 12, "#f8fafc", "#67e8f9")),
        new(
            Kind: BookCoverDesignKind.TransitMapFolio,
            Id: "transit-map-folio",
            Label: "Transit Map Folio",
            DemoTitleLines: ["Line", "Atlas"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Urban folio cover with sparse transit routes, station dots, and clear wayfinding rhythm.",
            CoverColors: new("#1e40af", "#3730a3", "#111827"),
            PageColors: new("#f8fafc", "#e2e8f0", "#cbd5e1"),
            LineStroke: "#94a3b8",
            Plate: BookCoverGeometry.CenteredPlate(76, 86, 68, 10, "#f8fafc", "#facc15")),
        new(
            Kind: BookCoverDesignKind.CompassFieldbook,
            Id: "compass-fieldbook",
            Label: "Compass Fieldbook",
            DemoTitleLines: ["True", "North"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Fieldbook cover with a compact compass rose, bearing ticks, and measured travel marks.",
            CoverColors: new("#334155", "#475569", "#0f172a"),
            PageColors: new("#f8fafc", "#e2e8f0", "#cbd5e1"),
            LineStroke: "#94a3b8",
            Plate: BookCoverGeometry.CenteredPlate(76, 86, 68, 8, "#f8fafc", "#fbbf24")),
        new(
            Kind: BookCoverDesignKind.AtlasPinboard,
            Id: "atlas-pinboard",
            Label: "Atlas Pinboard",
            DemoTitleLines: ["Pinned", "Atlas"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Pinboard atlas cover with route strings, map pins, and an editorial planning-board feel.",
            CoverColors: new("#92400e", "#a16207", "#451a03"),
            PageColors: new("#fffbeb", "#f5e3bf", "#d6c3a6"),
            LineStroke: "#b8a98e",
            Plate: BookCoverGeometry.CenteredPlate(76, 88, 68, 9, "#fffbeb", "#facc15")),
        new(
            Kind: BookCoverDesignKind.SeismographLog,
            Id: "seismograph-log",
            Label: "Seismograph Log",
            DemoTitleLines: ["Pulse", "Trace"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Signal-log cover with sharp trace lines, quiet sensor dots, and energetic measured motion.",
            CoverColors: new("#7f1d1d", "#991b1b", "#450a0a"),
            PageColors: new("#fff7ed", "#f1dfc8", "#d6c7b3"),
            LineStroke: "#b8a98e",
            Plate: BookCoverGeometry.CenteredPlate(76, 88, 68, 9, "#fff7ed", "#fecaca")),
        new(
            Kind: BookCoverDesignKind.AlpineTrailGuide,
            Id: "alpine-trail-guide",
            Label: "Alpine Trail Guide",
            DemoTitleLines: ["Trail", "Guide"],
            DemoTitleY: 103,
            DemoTitleDy: "1.2em",
            DemoTitleFontSize: "11.5",
            DemoTitleFill: "#111827",
            Note: "Trail-guide cover with crisp mountain ridges, switchback marks, and sparse route dots.",
            CoverColors: new("#14532d", "#166534", "#052e16"),
            PageColors: new("#f7fee7", "#e4efc8", "#cbd5c1"),
            LineStroke: "#a3a3a3",
            Plate: BookCoverGeometry.CenteredPlate(76, 88, 68, 10, "#f7fee7", "#bef264"))
    ];
}

public sealed record BookCoverDesignDefinition(
    BookCoverDesignKind Kind,
    string Id,
    string Label,
    IReadOnlyList<string> DemoTitleLines,
    int DemoTitleY,
    string DemoTitleDy,
    string DemoTitleFontSize,
    string DemoTitleFill,
    string Note,
    BookCoverDesignColors CoverColors,
    BookCoverDesignColors PageColors,
    string LineStroke,
    BookCoverTitlePlate Plate);

public sealed record BookCoverDesignColors(string Start, string Middle, string End);

public sealed record BookCoverTitlePlate(
    int X,
    int Y,
    int Width,
    int Height,
    int Radius,
    int InnerX,
    int InnerY,
    int InnerWidth,
    int InnerHeight,
    int InnerRadius,
    int TextX,
    string Fill,
    string Stroke);

public enum BookCoverDesignKind
{
    ClothHardback,
    DecorativeHardcover,
    FieldNotebook,
    PrismAtlas,
    DropletMonograph,
    TransitMapFolio,
    CompassFieldbook,
    AtlasPinboard,
    SeismographLog,
    AlpineTrailGuide
}
