extends: default

ignore: |
  **/bin/**
  **/obj/**

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  line-length: disable
  new-lines: disable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy: disable
