version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: BlazorAutoApp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "http://+:8080;https://+:8443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "localdevpassword"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./docker/https:/https:ro
      # Persist application storage (uploads, thumbnails, TUS temp)
      - ./data/storage:/app/Storage

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=ChangeMe123!
    ports:
      - "8081:80"    # UI
      - "5341:5341"  # Ingestion
    volumes:
      - seqdata:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 20

  redisinsight:
    image: redis/redisinsight:latest
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"  # Redis Insight UI
    volumes:
      - redisinsight:/data

volumes:
  pgdata:
  seqdata:
  redisinsight:
