all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/ship_deploy

  children:
    load_balancer:
      hosts:
        node-main:
          ansible_host: REPLACE_WITH_NODE_MAIN_LAN_IP

    app_servers:
      hosts:
        node-app1:
          ansible_host: REPLACE_WITH_NODE_APP1_LAN_IP
        node-app2:
          ansible_host: REPLACE_WITH_NODE_APP2_LAN_IP

    node_db:
      hosts:
        node-db:
          ansible_host: REPLACE_WITH_NODE_DB_LAN_IP
