all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/ship_deploy

  children:
    load_balancer:
      hosts:
        node-main:
          ansible_host: REPLACE_WITH_NODE_MAIN_LAN_IP

    app_servers:
      hosts:
        node-app-01:
          ansible_host: REPLACE_WITH_NODE_APP_01_LAN_IP
        node-app-02:
          ansible_host: REPLACE_WITH_NODE_APP_02_LAN_IP

    db_redis:
      hosts:
        node-db-redis:
          ansible_host: REPLACE_WITH_NODE_DB_REDIS_LAN_IP
