// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace BlazorAutoApp.Data.Migrations
{
    public partial class PivotHullImageRelation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "InspectionVesselPartId",
                table: "HullImages",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_HullImages_InspectionVesselPartId",
                table: "HullImages",
                column: "InspectionVesselPartId");

            migrationBuilder.AddForeignKey(
                name: "FK_HullImages_InspectionVesselParts_InspectionVesselPartId",
                table: "HullImages",
                column: "InspectionVesselPartId",
                principalTable: "InspectionVesselParts",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            // Drop old single-image column if it exists
            try
            {
                migrationBuilder.DropColumn(
                    name: "HullImageId",
                    table: "InspectionVesselParts");
            }
            catch { }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Recreate old column
            migrationBuilder.AddColumn<int>(
                name: "HullImageId",
                table: "InspectionVesselParts",
                type: "integer",
                nullable: true);

            migrationBuilder.DropForeignKey(
                name: "FK_HullImages_InspectionVesselParts_InspectionVesselPartId",
                table: "HullImages");

            migrationBuilder.DropIndex(
                name: "IX_HullImages_InspectionVesselPartId",
                table: "HullImages");

            migrationBuilder.DropColumn(
                name: "InspectionVesselPartId",
                table: "HullImages");
        }
    }
}

