// <auto-generated />
using System;
using BlazorAutoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorAutoApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250913080953_VesselPartDetails")]
    partial class VesselPartDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorAutoApp.Core.Features.HullImages.HullImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AiHullScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("InspectionVesselPartId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("BoatyBoat");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionVesselPartId");

                    b.ToTable("HullImages", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("InspectionType")
                        .HasColumnType("integer");

                    b.Property<string>("VesselName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("InspectionFlows", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionVesselPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId", "PartCode");

                    b.ToTable("InspectionVesselParts", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vessels", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.StartHullInspectionEmail.CompanyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("HasActivatedLatestInspectionEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CompanyDetails", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VerifyInspectionEmail.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Inspections", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.CoatingCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blisters")
                        .HasColumnType("boolean");

                    b.Property<int>("IntactPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("Peeling")
                        .HasColumnType("boolean");

                    b.Property<bool>("Scratching")
                        .HasColumnType("boolean");

                    b.Property<int>("VesselPartDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VesselPartDetailsId")
                        .IsUnique();

                    b.ToTable("CoatingConditions", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.FoulingObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoveragePercent")
                        .HasColumnType("integer");

                    b.Property<int>("FoulingType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("VesselPartDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VesselPartDetailsId");

                    b.ToTable("FoulingObservations", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Corrosion")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cracks")
                        .HasColumnType("boolean");

                    b.Property<bool>("Dents")
                        .HasColumnType("boolean");

                    b.Property<int>("IntegrityPercent")
                        .HasColumnType("integer");

                    b.Property<int>("VesselPartDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VesselPartDetailsId")
                        .IsUnique();

                    b.ToTable("HullConditions", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<int>("VesselPartDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VesselPartDetailsId")
                        .IsUnique();

                    b.ToTable("HullRatings", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InspectionVesselPartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionVesselPartId")
                        .IsUnique();

                    b.ToTable("VesselPartDetails", (string)null);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.HullImages.HullImage", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionVesselPart", null)
                        .WithMany("HullImages")
                        .HasForeignKey("InspectionVesselPartId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionVesselPart", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionFlow", null)
                        .WithMany("VesselParts")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VerifyInspectionEmail.Inspection", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.StartHullInspectionEmail.CompanyDetail", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.CoatingCondition", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", null)
                        .WithOne("Coating")
                        .HasForeignKey("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.CoatingCondition", "VesselPartDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.FoulingObservation", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", null)
                        .WithMany("Fouling")
                        .HasForeignKey("VesselPartDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullCondition", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", null)
                        .WithOne("Hull")
                        .HasForeignKey("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullCondition", "VesselPartDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullRating", b =>
                {
                    b.HasOne("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", null)
                        .WithOne("Rating")
                        .HasForeignKey("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.HullRating", "VesselPartDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionFlow", b =>
                {
                    b.Navigation("VesselParts");
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.InspectionFlow.InspectionVesselPart", b =>
                {
                    b.Navigation("HullImages");
                });

            modelBuilder.Entity("BlazorAutoApp.Core.Features.Inspections.VesselPartDetails.VesselPartDetails", b =>
                {
                    b.Navigation("Coating");

                    b.Navigation("Fouling");

                    b.Navigation("Hull");

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
