name: Auto Merge Dependabot Updates

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'dependabot[bot]' &&
      github.event.workflow_run.pull_requests[0].number != null
    runs-on: ubuntu-24.04
    steps:
      - name: Approve Pull Request
        run: gh pr review "${{ github.event.workflow_run.pull_requests[0].number }}" --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Merge Pull Request
        run: gh pr merge "${{ github.event.workflow_run.pull_requests[0].number }}" --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
